

## eureka 高可用，注册之后，会将eureka注册中心的数据先同步，再添加实例，保证高可用。
# peer1上的eureka注册了 peer2,peer3, peer2上的eureka注册了 peer1,peer3. 这样
# Peer1启动之后，会先同步数据到 注册中心，因为在peer2上注册了peer1.所以peer2上会有
# peer1上同步的信息，即 peer2上的服务会有 peer1,peer2,peer3。


spring:
  application:
    name: EUREKA-HA

---
server:
  port: 8762
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8763/eureka/,http://peer3:8764/eureka/
  server:
    enable-self-preservation: false

---

server:
  port: 8763
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer3:8764/eureka/
  server:
    enable-self-preservation: false

---
server:
  port: 8764
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/
  server:
    enable-self-preservation: false