server:
  port: 8761

#spring:
 # security:
  #  user:
   #   name: user # 配置登录的账号是user
    #  password: haoliang11 #配置登录的密码是haoliang11


eureka:
  client:
    ## 不把eureka设置成客户端
    register-with-eureka: false
    fetch-registry: false
    ## 把eureka 注册到哪个url上
    service-url:
      #defaultZone: http://user:haoliang11@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  # 等于false之后，变成自我模式，90秒之后自动剔除关闭的服务。生产环境不要关闭自我模式
  server:
    enable-self-preservation: false



