spring:
  application:
    name: microservice-consumer-movie-feign-withhystrix

server:
  port: 8077

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#健康检查
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [health,info]
logging:
  level:
    com.haol.cloud.feign.UserFeignClient: debug
## 启用hystrix
feign:
  hystrix:
    enabled: true

